package be.t_ars.xtouch.xctl

interface IXTouchEvents {
	fun channelRecPressed(channel: Int, down: Boolean)
	fun channelSoloPressed(channel: Int, down: Boolean)
	fun channelMutePressed(channel: Int, down: Boolean)
	fun channelSelectPressed(channel: Int, down: Boolean)
	fun knobPressed(knob: Int, down: Boolean)
	fun encoderTrackPressed(down: Boolean)
	fun encoderSendPressed(down: Boolean)
	fun encoderPanPressed(down: Boolean)
	fun encoderPluginPressed(down: Boolean)
	fun encoderEqPressed(down: Boolean)
	fun encoderInstPressed(down: Boolean)
	fun previousBankPressed(down: Boolean)
	fun nextBankPressed(down: Boolean)
	fun previousChannelPressed(down: Boolean)
	fun nextChannelPressed(down: Boolean)
	fun flipPressed(down: Boolean)
	fun globalViewPressed(down: Boolean)
	fun displayPressed(down: Boolean)
	fun smptePressed(down: Boolean)
	fun functionPressed(function: Int, down: Boolean)
	fun midiTracksPressed(down: Boolean)
	fun inputsPressed(down: Boolean)
	fun audioTracksPressed(down: Boolean)
	fun audioInstPressed(down: Boolean)
	fun auxPressed(down: Boolean)
	fun busesPressed(down: Boolean)
	fun outputsPressed(down: Boolean)
	fun userPressed(down: Boolean)
	fun modifyPressed(modify: Int, down: Boolean)
	fun automationPressed(automation: Int, down: Boolean)
	fun utiliyPressed(utility: Int, down: Boolean)
	fun faderPressed(channel: Int, down: Boolean)
	fun mainFaderPressed(down: Boolean)
	fun knobRotated(knob: Int, right: Boolean)
	fun faderMoved(channel: Int, position: Int)
	fun mainFaderMoved(position: Int)
	fun systemMessage(message: ByteArray)
}