name: Cleanup

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'be.t_ars.proxy'
          package-type: 'maven'
          min-versions-to-keep: 1